### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by siddharthbiju** [MayankFawkes/BSNL_FTTH#1]
NOT FOUND, Reason: No session found with sessionIP: ........

**Comment by MayankFawkes** [comment]
Yes we are aware from this error and we are working on it, in few days we will release another update for these bug fix. Thanks for your patience.

**Comment by MayankFawkes** [comment]
This update will fix your problem [download](https://github.com/MayankFawkes/BSNL_FTTH/releases/tag/v1.4.0)
